# Generated by Django 5.1.1 on 2024-10-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=30)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("median", models.DecimalField(decimal_places=2, max_digits=10)),
                ("percentile_25", models.DecimalField(decimal_places=2, max_digits=10)),
                ("percentile_75", models.CharField(max_length=10)),
                ("frequency", models.CharField(max_length=30)),
                ("frequency_legend", models.CharField(max_length=30)),
            ],
        ),
    ]
