# Generated by Django 5.1.2 on 2024-10-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="frequency",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="region",
            name="percentile_75",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
