# Generated by Django 5.1.2 on 2024-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_region_region_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(max_length=30),
        ),
    ]
