# Generated by Django 5.1.2 on 2024-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_region_region_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
